---
deployment:
 tasks:
  - export DEPLOYPATH=/home/rosbnuod/public_html/
  - /bin/cp -R repositories/rbg-dev.com $DEPLOYPATH
  #- /bin/cp app/page $DEPLOYPATH
  #- /bin/cp app/globals.css $DEPLOYPATH
